apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microk8s-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yashikota/microk8s-test.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
